
INSERT INTO industries (name, code, description, status) VALUES
('Aerospace & Defense', 'AERO', 'Aircraft, spacecraft, defense systems, and military equipment manufacturing', 'active'),
('Airlines & Aviation', 'AVTN', 'Commercial and private air transportation services', 'active'),
('Apparel & Fashion', 'FASH', 'Clothing, footwear, and fashion accessories design and retail', 'active'),
('Architecture & Planning', 'ARCH', 'Architectural design, urban planning, and landscape architecture', 'active'),
('Banking & Financial Services', 'BANK', 'Commercial banking, investment banking, and financial services', 'active'),
('Biotechnology', 'BIOT', 'Biological research, genetic engineering, and biopharmaceuticals', 'active'),
('Broadcasting & Media', 'MEDIA', 'Television, radio, streaming, and digital media production', 'active'),
('Chemicals', 'CHEM', 'Chemical manufacturing, petrochemicals, and specialty chemicals', 'active'),
('Civil Engineering', 'CIVIL', 'Infrastructure development, roads, bridges, and public works', 'active'),
('Computer Hardware', 'CHWRE', 'Computer systems, peripherals, and hardware components', 'active'),
('Computer Software', 'CSWRE', 'Software development, SaaS, and enterprise applications', 'active'),
('Consumer Electronics', 'CELEC', 'Electronic devices, gadgets, and consumer technology products', 'active'),
('Consumer Goods', 'CGOODS', 'Household products, personal care, and everyday consumer items', 'active'),
('Cosmetics & Beauty', 'COSM', 'Skincare, makeup, fragrances, and beauty products', 'active'),
('Dairy & Livestock', 'DAIRY', 'Dairy farming, livestock rearing, and animal husbandry', 'active'),
('E-Commerce', 'ECOM', 'Online retail, digital marketplaces, and internet commerce', 'active'),
('Electrical & Electronic Manufacturing', 'ELEC', 'Electrical equipment, components, and electronic systems', 'active'),
('Energy & Utilities', 'ENRGY', 'Electricity, gas, water utilities, and energy distribution', 'active'),
('Entertainment & Leisure', 'ENTRT', 'Amusement parks, gaming, recreation, and entertainment venues', 'active'),
('Environmental Services', 'ENVIR', 'Waste management, recycling, pollution control, and environmental consulting', 'active'),
('Events & Conferences', 'EVENT', 'Event planning, conference management, and exhibitions', 'active'),
('Fishery & Aquaculture', 'FISH', 'Commercial fishing, fish farming, and seafood processing', 'active'),
('Food & Beverage', 'FOOD', 'Food production, processing, restaurants, and beverage manufacturing', 'active'),
('Forestry & Timber', 'FORST', 'Forestry management, logging, and timber products', 'active'),
('Freight & Logistics', 'LOGIS', 'Shipping, freight forwarding, warehousing, and supply chain', 'active'),
('Furniture & Woodworking', 'FURN', 'Furniture manufacturing, carpentry, and wood products', 'active'),
('Glass, Ceramics & Concrete', 'GLASS', 'Glass manufacturing, ceramics, pottery, and concrete products', 'active'),
('Government & Public Administration', 'GOVT', 'Government agencies, public services, and civil administration', 'active'),
('Graphic Design & Visual Arts', 'GRFX', 'Graphic design, illustration, photography, and visual communication', 'active'),
('Hospitality & Tourism', 'HOSP', 'Hotels, resorts, travel agencies, and tourism services', 'active'),
('Human Resources & Staffing', 'HRSTA', 'Recruitment, staffing agencies, HR consulting, and workforce solutions', 'active'),
('Import & Export', 'IMPEX', 'International trade, import/export services, and customs brokerage', 'active'),
('Information Technology & Services', 'ITSER', 'IT consulting, managed services, system integration, and IT support', 'active'),
('Insurance', 'INSUR', 'Life, health, property, and casualty insurance services', 'active'),
('Interior Design', 'INTDS', 'Interior decoration, space planning, and home staging', 'active'),
('Internet & Telecommunications', 'TELCO', 'Internet service providers, telecom networks, and communications', 'active'),
('Investment & Fund Management', 'INVST', 'Investment management, venture capital, private equity, and hedge funds', 'active'),
('Jewelry & Luxury Goods', 'JEWEL', 'Jewelry manufacturing, gemstones, watches, and luxury accessories', 'active'),
('Legal Services', 'LEGAL', 'Law firms, legal consulting, notary services, and paralegal services', 'active'),
('Library & Information Sciences', 'LIBRY', 'Libraries, archives, information management, and research services', 'active'),
('Machinery & Industrial Equipment', 'MACHI', 'Industrial machinery, equipment manufacturing, and heavy equipment', 'active'),
('Management Consulting', 'MGCON', 'Business consulting, strategy advisory, and management services', 'active'),
('Maritime & Shipping', 'MARIT', 'Shipping lines, port operations, and maritime transport', 'active'),
('Marketing & Advertising', 'MKTNG', 'Digital marketing, advertising agencies, PR, and brand management', 'active'),
('Mechanical & Industrial Engineering', 'MECH', 'Mechanical systems, industrial processes, and engineering services', 'active'),
('Medical Devices & Equipment', 'MEDDV', 'Medical device manufacturing, surgical instruments, and diagnostic equipment', 'active'),
('Mining & Metals', 'MINNG', 'Mining operations, metal extraction, and mineral processing', 'active'),
('Music & Recording', 'MUSIC', 'Music production, recording studios, and music distribution', 'active'),
('Nanotechnology', 'NANO', 'Nanoscale materials, devices, and applications', 'active'),
('Non-Profit & NGO', 'NPROF', 'Charitable organizations, NGOs, social enterprises, and foundations', 'active'),
('Oil & Gas', 'OILGS', 'Oil exploration, gas production, refining, and petroleum products', 'active'),
('Packaging & Containers', 'PACKG', 'Packaging materials, containers, and packaging solutions', 'active'),
('Paper & Forest Products', 'PAPER', 'Paper manufacturing, pulp production, and paper products', 'active'),
('Performing Arts', 'PFART', 'Theater, dance, live performances, and performing arts management', 'active'),
('Pharmaceuticals', 'PHARM', 'Drug manufacturing, pharmaceutical research, and drug distribution', 'active'),
('Photography', 'PHOTO', 'Professional photography, photo studios, and imaging services', 'active'),
('Plastics & Rubber', 'PLAST', 'Plastic manufacturing, rubber products, and polymer processing', 'active'),
('Printing & Publishing', 'PRINT', 'Commercial printing, book publishing, and print media', 'active'),
('Professional Training & Coaching', 'TRAIN', 'Corporate training, executive coaching, and professional development', 'active'),
('Public Relations', 'PUBRL', 'PR agencies, communications, and reputation management', 'active'),
('Railroad & Rail Transport', 'RAIL', 'Railway operations, rail freight, and rail infrastructure', 'active'),
('Renewable Energy', 'RENEW', 'Solar, wind, hydro, geothermal, and other renewable energy sources', 'active'),
('Research & Development', 'RNDEV', 'Scientific research, product development, and innovation labs', 'active'),
('Robotics & Automation', 'ROBOT', 'Industrial robots, automation systems, and AI-driven machinery', 'active'),
('Security & Investigations', 'SECUR', 'Private security, surveillance, investigations, and cybersecurity', 'active'),
('Semiconductors', 'SEMIC', 'Semiconductor manufacturing, chip design, and microelectronics', 'active'),
('Shipbuilding', 'SHIPB', 'Ship construction, boat building, and marine vessel manufacturing', 'active'),
('Social Services & Welfare', 'SOCWL', 'Social work, community services, and welfare programs', 'active'),
('Sports & Recreation', 'SPORT', 'Professional sports, fitness centers, sports equipment, and recreation', 'active'),
('Supermarkets & Grocery', 'GROCY', 'Grocery retail, supermarket chains, and food distribution', 'active'),
('Textiles & Apparel Manufacturing', 'TXTIL', 'Textile manufacturing, fabric production, and garment making', 'active'),
('Tobacco', 'TOBAC', 'Tobacco farming, cigarette manufacturing, and tobacco products', 'active'),
('Translation & Linguistics', 'TRANSLG', 'Translation services, interpretation, and language solutions', 'active'),
('Transportation & Warehousing', 'TRWHS', 'Public transport, trucking, warehousing, and distribution', 'active'),
('Veterinary Services', 'VETRY', 'Animal healthcare, veterinary clinics, and pet care services', 'active'),
('Waste Management', 'WASTE', 'Solid waste collection, disposal, recycling, and waste treatment', 'active'),
('Water Treatment & Supply', 'WATER', 'Water purification, treatment plants, and water supply systems', 'active'),
('Wholesale & Distribution', 'WHLSL', 'Wholesale trade, distribution networks, and bulk supply', 'active'),
('Wine & Spirits', 'WINES', 'Winemaking, distilleries, breweries, and alcoholic beverage production', 'active'),
('Wireless & Mobile', 'WIRLS', 'Mobile networks, wireless technology, and cellular services', 'active'),
('Writing & Editing', 'WRITE', 'Content writing, copywriting, editing, and publishing services', 'active'),
('Artificial Intelligence', 'AINML', 'AI research, machine learning, deep learning, and intelligent systems', 'active'),
('Blockchain & Cryptocurrency', 'BLKCH', 'Blockchain technology, cryptocurrency, DeFi, and Web3', 'active'),
('Cloud Computing', 'CLOUD', 'Cloud infrastructure, cloud services, and cloud-based solutions', 'active'),
('Cybersecurity', 'CYBER', 'Information security, threat detection, and data protection', 'active'),
('Data Analytics & Big Data', 'DATAA', 'Data science, business intelligence, and big data analytics', 'active'),
('Digital Health & Telemedicine', 'DHLTH', 'Telehealth, digital therapeutics, and health technology', 'active'),
('FinTech', 'FNTCH', 'Financial technology, digital payments, and banking innovation', 'active'),
('Gaming & Esports', 'GAMES', 'Video game development, esports, and interactive entertainment', 'active'),
('Green Technology', 'GRNTC', 'Clean technology, sustainable innovation, and eco-friendly solutions', 'active'),
('Space Technology', 'SPACE', 'Satellite technology, space exploration, and space commerce', 'active'),
('3D Printing & Additive Manufacturing', '3DPRN', '3D printing technology, additive manufacturing, and rapid prototyping', 'active'),
('Augmented & Virtual Reality', 'ARVR', 'AR/VR hardware, software, immersive experiences, and metaverse', 'active'),
('Drones & UAV', 'DRONE', 'Drone manufacturing, UAV services, and aerial technology', 'active'),
('EdTech', 'EDTCH', 'Educational technology, e-learning platforms, and digital education', 'active'),
('Electric Vehicles', 'EVHCL', 'Electric car manufacturing, EV charging, and electric mobility', 'active'),
('Internet of Things (IoT)', 'IOT', 'Connected devices, smart sensors, and IoT platforms', 'active'),
('PropTech', 'PRPTC', 'Property technology, real estate tech, and smart buildings', 'active'),
('Quantum Computing', 'QCOMP', 'Quantum processors, quantum algorithms, and quantum research', 'active'),
('Supply Chain & Procurement', 'SUPLC', 'Supply chain management, procurement, and sourcing solutions', 'active'),
('Wearable Technology', 'WEAR', 'Smartwatches, fitness trackers, and wearable devices', 'active');
